orbs:
  dotnet-sonarscanner: storytel/dotnet-sonarscanner@1.4.3
  
 jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - dotnet-sonarscanner/sonar-end
workflows:
  example-workflow:
    jobs:
      - example-job